/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex;

import context.DAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.employees;

/**
 *
 * @author luat
 */
public class Main extends javax.swing.JFrame {

    DAO d = new DAO();
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        loadEmployees();
        btSort.setEnabled(false);
    }

    public void loadEmployees() {
        ArrayList<employees> arr = new ArrayList<>();
        arr = d.getAllEmp();
        dtm = (DefaultTableModel) tbList.getModel();
        dtm.setRowCount(0);
        String code;
        String name;
        double salary;
        double bonus;
        for (employees e : arr) {
            code = e.getCode();
            name = e.getName();
            salary = e.getSalary();
            bonus = e.getBonus();
            dtm.insertRow(dtm.getRowCount(), new Object[]{code, name, salary, bonus});
        }
    }

    public void orderEmployees(String order) {
        ArrayList<employees> arr = new ArrayList<>();
        arr = d.getAllOrderEmp(order);
        dtm = (DefaultTableModel) tbList.getModel();
        dtm.setRowCount(0);
        String code;
        String name;
        double salary;
        double bonus;
        for (employees e : arr) {
            code = e.getCode();
            name = e.getName();
            salary = e.getSalary();
            bonus = e.getBonus();
            dtm.insertRow(dtm.getRowCount(), new Object[]{code, name, salary, bonus});
        }
    }

    public ArrayList<employees> searchByCode(String code) {
        ArrayList<employees> arr = new ArrayList<>();
        arr = d.searchByCode(code);
        return arr;
    }

    public boolean checkDuplicate(String code) {
        ArrayList<employees> arr = new ArrayList<>();
        arr = d.getAllEmp();
        for (employees object : arr) {
            if (code.equals(object.getCode())) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txName = new javax.swing.JTextField();
        txSalary = new javax.swing.JTextField();
        txBonus = new javax.swing.JTextField();
        txSearch = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btSort = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txResult = new javax.swing.JTextArea();
        rbAsc = new javax.swing.JRadioButton();
        rbDes = new javax.swing.JRadioButton();
        txCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employees management");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter new employee:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter code to be searched:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Code:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Salary:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Bonus:");

        txName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txSalary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txBonus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txSearchFocusGained(evt);
            }
        });
        txSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSearchActionPerformed(evt);
            }
        });

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btSort.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSort.setText("Sort");
        btSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Search result:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tbList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Salary", "Bonus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbList);

        txResult.setColumns(20);
        txResult.setRows(5);
        jScrollPane2.setViewportView(txResult);

        buttonGroup1.add(rbAsc);
        rbAsc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbAsc.setText("Asc");
        rbAsc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbAscStateChanged(evt);
            }
        });

        buttonGroup1.add(rbDes);
        rbDes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbDes.setText("Des");
        rbDes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDesStateChanged(evt);
            }
        });

        txCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btAdd)
                                                .addGap(18, 18, 18)
                                                .addComponent(btSort)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbAsc)))
                                        .addGap(18, 18, 18)
                                        .addComponent(rbDes)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btSort)
                    .addComponent(rbAsc)
                    .addComponent(rbDes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:

        try {
            if (txCode.getText().isEmpty() || txName.getText().isEmpty() || txSalary.getText().isEmpty() || txBonus.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Không được để trống các thành phần!");
                return;
            }
            String code = txCode.getText();
            String name = txName.getText();
            double salary = Double.parseDouble(txSalary.getText());
            double bonus = Double.parseDouble(txBonus.getText());
            if (!checkDuplicate(code)) {
                JOptionPane.showMessageDialog(null, "Code bị trùng.Thử lại!");
                return;
            }
            if (d.addEmployees(code, name, salary, bonus)) {
                JOptionPane.showMessageDialog(null, "Add thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "Add thất bại");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sai định dạng số.");
            System.out.println("" + e.getMessage());
            return;
        }
        loadEmployees();
    }//GEN-LAST:event_btAddActionPerformed

    private void rbAscStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbAscStateChanged
        // TODO add your handling code here:
        if (rbAsc.isSelected()) {
            btSort.setEnabled(true);
        }
    }//GEN-LAST:event_rbAscStateChanged

    private void rbDesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDesStateChanged
        // TODO add your handling code here:
        if (rbDes.isSelected()) {
            btSort.setEnabled(true);
        }
    }//GEN-LAST:event_rbDesStateChanged

    private void btSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortActionPerformed
        // TODO add your handling code here:
        if (rbAsc.isSelected()) {
            orderEmployees("ASC");
        } else {
            orderEmployees("DESC");
        }
    }//GEN-LAST:event_btSortActionPerformed

    private void txSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSearchActionPerformed
        // TODO add your handling code here:
        txResult.setText("");
        String result = "";
        String codeSearch = txSearch.getText();
        ArrayList<employees> arr = searchByCode(codeSearch);
        if (arr.isEmpty()) {
            result = "Không có kết quả tìm kiếm!";
        } else {
            for (employees e : arr) {
                result += "Code:" + e.getCode() + " |Name:" + e.getName() + " |Salary:" + e.getSalary() + " |Bonus: " + e.getBonus() + "\n";
            }
        }
        txResult.setText(result);
    }//GEN-LAST:event_txSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txResult.setText("");
        String result = "";
        String codeSearch = txSearch.getText();
        ArrayList<employees> arr = searchByCode(codeSearch);
        if (arr.isEmpty()) {
            result = "Không có kết quả tìm kiếm!";
        } else {
            for (employees e : arr) {
                result += "Code:" + e.getCode() + " |Name:" + e.getName() + " |Salary:" + e.getSalary() + " |Bonus: " + e.getBonus() + "\n";
            }
        }
        txResult.setText(result);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSearchFocusGained
        // TODO add your handling code here:
        txResult.setText("");
    }//GEN-LAST:event_txSearchFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btSort;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAsc;
    private javax.swing.JRadioButton rbDes;
    private javax.swing.JTable tbList;
    private javax.swing.JTextField txBonus;
    private javax.swing.JTextField txCode;
    private javax.swing.JTextField txName;
    private javax.swing.JTextArea txResult;
    private javax.swing.JTextField txSalary;
    private javax.swing.JTextField txSearch;
    // End of variables declaration//GEN-END:variables
}
